name: Auto Update Repository

on:
  push:
    branches:
      - main  # 或者你想要自动更新的分支

jobs:
  auto-update:
    runs-on: windows-latest

    steps:
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto-update on push"
        git push origin main  # 确保你有正确的推送权限设置
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
